version: '3.8'

services:
  db:
    image: mongo:7.0
    container_name: parser_mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: parser
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - parser_network

  web:
    build: .
    container_name: parser_django
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-change-this-in-production
      - MONGO_HOST=db
      - MONGO_PORT=27017
    networks:
      - parser_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  mongodb_data:
  media_volume:

networks:
  parser_network:
    driver: bridge

