# Generated by Django 4.2.10 on 2025-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('parties', models.JSONField(blank=True, default=dict)),
                ('account_info', models.JSONField(blank=True, default=dict)),
                ('financial_details', models.JSONField(blank=True, default=dict)),
                ('payment_structure', models.JSONField(blank=True, default=dict)),
                ('revenue_classification', models.JSONField(blank=True, default=dict)),
                ('sla', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('gaps', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
